version: "3"
services:
  frontend:
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    environment:
      PORT: ${FRONTEND_PORT}
    network_mode: host
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  pg:
    image: postgres:13.2
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PG_LOCAL_PORT}:5432

  pgadmin:
    image: dpage/pgadmin4:5.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80

  redis:
    image: redis:6.2
    ports:
      - ${REDIS_PORT}:6379
