version: "3"
services:
  backend:
    build:
      context: backend
      dockerfile: dev.Dockerfile
    environment:
      DATABASE_URL: postgres://${PG_USERNAME}:${PG_PASSWORD}@pg/${PG_DATABASE}
    ports:
      - ${BACKEND_PORT}:3000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/target

  pg:
    image: postgres:13.2
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:5.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
