version: "3"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://${PG_USERNAME}:${PG_PASSWORD}@pg/${PG_DATABASE}
    ports:
      - ${BACKEND_PORT}:3000

  pg:
    image: postgres:13.2
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  redis:
    image: redis:6.2
    ports:
      - ${REDIS_PORT}:6379
