[package]
name = "backend"
version = "0.1.0"
authors = ["Rasmus Rosengren <rasmus.rosengren@pm.me>"]
edition = "2018"

[dependencies]
actix-web = "3.3"
actix-web-httpauth = "0.5"
anyhow = "1.0"
chrono = "0.4"
dotenv = "0.15"
juniper = { version = "0.15", features = ["chrono"] }
juniper_actix = "0.2"
sqlx = { version = "0.4", features = ["runtime-actix-rustls", "postgres", "macros", "migrate", "chrono", "uuid", "offline"] }
uuid = "0.8"
